# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jokes of Norris' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jokes of Norris
  pod 'XCoordinator/RxSwift', '~> 2.0'
  pod "TinyConstraints"
  pod 'Alamofire', '~> 5.2'

  target 'Jokes of NorrisTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Jokes of NorrisUITests' do
    # Pods for testing
  end

end
